<!DOCTYPE html>
<?php include_once "diff_tester.php"; ?>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
    <meta name="description" content="description du site">
    <meta name="author" content="Aiello Antoine">
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<title>Diff Tester</title>
    <link rel="stylesheet" href="css/fk-css_html.min.css">
    <link rel="stylesheet" href="css/fk-framework.min.css">
		<link rel="stylesheet" href="css/master.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
		<link rel="shortcut icon" href="pics/logo.png"><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<!-- add scripts to the header to listnen consoles -->
		<script type="text/javascript" src="js/functions.min.js" charset="utf-8"></script>
		<script type="text/javascript" src="js/objects.min.js" charset="utf-8"></script>
		<script type="text/javascript" src="js/fk-framework.min.js" charset="utf-8"></script>
	</head>
